name: py3
channels:
  - pytorch
  - conda-forge
  - dglteam
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - astroid=2.2.5
  - attrs=19.1.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.1
  - blas=1.0
  - bleach=3.1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.0
  - click=7.1.2
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - dgl=0.4
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - glob2=0.7
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.4
  - ipdb=0.12.3
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.2
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.13
  - libxgboost=0.90
  - libxml2=2.9.9
  - llvmlite=0.37.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - ninja=1.10.2
  - nltk=3.5
  - notebook=6.0.1
  - numba=0.54.1
  - numexpr=2.7.3
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1l
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py-xgboost=0.90
  - pycparser=2.20
  - pygments=2.4.2
  - pylint=2.3.1
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.4
  - python-dateutil=2.8.0
  - python_abi=3.7
  - pytorch=1.7.1
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - regex=2021.4.4
  - scikit-learn=0.21.2
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.2.0
  - sip=4.19.8
  - soupsieve=1.9.5
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tbb=2021.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tornado=6.0.3
  - traitlets=4.3.2
  - typing_extensions=3.7.4.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.5.1
  - xgboost=0.90
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - abed==0.1.2
    - absl-py==0.11.0
    - aiohttp==3.7.4.post0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - backports-lzma==0.0.14
    - bcrypt==3.2.0
    - bz2file==0.98
    - cachetools==4.0.0
    - chardet==3.0.4
    - click-plugins==1.1.1
    - cligj==0.7.2
    - covidcast==0.1.5
    - cryptography==36.0.0
    - delphi-epidata==0.2.9
    - descartes==1.1.0
    - dominate==2.6.0
    - epiweeks==2.1.1
    - fabric3==1.14.post1
    - fastdtw==0.3.4
    - fiona==1.8.20
    - flatbuffers==1.12
    - gast==0.3.3
    - geopandas==0.9.0
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-auth==1.10.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.8
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.5
    - ipyparallel==6.3.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.1.1
    - mpi4py==3.1.3
    - multidict==5.1.0
    - munch==2.5.0
    - nose==1.3.7
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.2.3
    - paramiko==2.8.0
    - pip==21.2.4
    - progressbar==2.5
    - protobuf==3.11.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pynacl==1.4.0
    - pyproj==3.1.0
    - pyreadr==0.4.2
    - pyyaml==5.4.1
    - random-word==1.0.4
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - shapely==1.7.1
    - six==1.15.0
    - smmap==5.0.0
    - tabulate==0.8.9
    - tenacity==8.0.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - torch-tb-profiler==0.2.1
    - tqdm==4.54.1
    - typed-ast==1.4.2
    - urllib3==1.25.6
    - werkzeug==0.16.0
    - wheel==0.36.2
    - wrapt==1.12.1
    - yarl==1.6.3
